### ISSUE TITLE
example needed

### ISSUE THREAD

**Issue by toinsson** [vahndi/SyNaPSE#33]
Hello, 

the repo looks nice. One issue: what does it do? Executing `python SyNaPSE` opens the GUI but there do not seem to be anything to interact with, except the `calculate output` button that returns `No Calculation Selected`.

**Comment by vahndi** [comment]
Hi, are you using a mac? Go to the python menu bar and try Add Calculation / sklearn and generate some data, or use the pandas menu to read a dataframe in.

**Comment by vahndi** [comment]
Added a get started section to readme.md

**Comment by toinsson** [comment]
yes, was using a Mac and did not see the menu.. Tried on Linux, and menu is attached to the window. Assume on Mac it is anchor to the top of the screen : ) will double check later.

**Comment by toinsson** [comment]
thanks for the update on readme
